services:
  finsight-builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: finsight-club-dashboard
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=main.py
    restart: unless-stopped
